a=input("Enter the Word :- ")
print("Length of word = ",len(a))
print("Change to upper case :-", a.upper())
print("Change to lower case :-", a.lower())
print("Remove all whitespace :-", a.strip())
print("Remove all trailing character :-", a.rstrip())
print("Replacing the Words:- ",a.replace(" "," Sir"))
print("List in all words :-", a.split(" "))
print("Captlize all words :-",a.capitalize())
b=input("Enter the Letter :-")
print("Couting how names a letter in sentence :-",a.count(b))
print("Put fullstop at end of words :- ",a.endswith(""))